import {
  PatientProfile,
  CaregiverProfile,
  FamilyMember,
  Medication,
  CognitiveSession,
  CulturalCard,
  BrainQuestPuzzle,
  RoutineCard,
  SoundCard,
  FolkSongCard,
} from '../types';

export const demoPatients: PatientProfile[] = [
  {
    id: 'pat-1',
    name: 'Bhaben Hazarika',
    age: 74,
    language: 'as',
    preferredLanguage: 'as',
    location: 'Guwahati, Assam (Silpukhuri)',
    diagnosisStage: 'Mild Cognitive Impairment',
    bio: 'Retired high school headmaster from Tezpur. Loves singing Bhupen Hazarika songs, tending to orchids, and drinking morning Assam black tea with cardamom.',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=300&q=80',
    emergencyContact: {
      name: 'Ananya Hazarika (Daughter)',
      relation: 'Daughter & Primary Caregiver',
      phone: '+91 98640 12345',
      address: 'House #42, Silpukhuri Main Road, Guwahati 781003',
    },
  },
  {
    id: 'pat-2',
    name: 'Monimala Roy',
    age: 71,
    language: 'bn',
    preferredLanguage: 'bn',
    location: 'Silchar, Assam (Cachar)',
    diagnosisStage: 'Early Stage',
    bio: 'Former primary school teacher and master kantha embroidery artist. Passionate about Rabindra Sangeet and cooking traditional Sylheti fish curry.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    emergencyContact: {
      name: 'Subhash Roy (Son)',
      relation: 'Son',
      phone: '+91 94350 56789',
      address: 'Lane 4, Ambicapatty, Silchar 788004',
    },
  },
  {
    id: 'pat-3',
    name: 'Iboyaima Singh',
    age: 76,
    language: 'mni',
    preferredLanguage: 'mni',
    location: 'Imphal, Manipur (Uripok)',
    diagnosisStage: 'Mild Cognitive Impairment',
    bio: 'Veteran traditional Pung (drum) artist and Loktak Lake conservation enthusiast. Enjoys morning walks by Kangla Fort.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    emergencyContact: {
      name: 'Bembem Devi (Daughter-in-law)',
      relation: 'Daughter-in-law',
      phone: '+91 98560 98765',
      address: 'Uripok Achom Leikai, Imphal West 795001',
    },
  },
];

export const demoCaregiver: CaregiverProfile = {
  id: 'cg-1',
  name: 'Ananya Hazarika',
  relation: 'Daughter',
  phone: '+91 98640 12345',
  email: 'ananya.hazarika@gmail.com',
  burnoutScore: 32, // Zarit score indicator
};

export const demoFamilyMembers: FamilyMember[] = [
  {
    id: 'fam-1',
    name: 'Ananya Hazarika',
    relation: 'Daughter',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    memoryHint: 'Lives with you in Guwahati; brings your morning medicine and tea.',
    favoriteMemory: 'Taught her how to ride a bicycle by Dighalipukhuri lake.',
    hometown: 'Guwahati, Assam',
  },
  {
    id: 'fam-2',
    name: 'Arnob Hazarika',
    relation: 'Grandson',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    memoryHint: 'Studies engineering at IIT Guwahati; loves hearing your folk tales.',
    favoriteMemory: 'Building bamboo kites together every Rongali Bihu.',
    hometown: 'Guwahati, Assam',
  },
  {
    id: 'fam-3',
    name: 'Late Pranati Hazarika',
    relation: 'Beloved Wife',
    photoUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=400&q=80',
    memoryHint: 'Married in Tezpur in 1975; made the sweetest pitha for Bihu.',
    favoriteMemory: 'Planting your first orchid garden in Tezpur behind the old headmaster quarters.',
    hometown: 'Tezpur, Assam',
  },
  {
    id: 'fam-4',
    name: 'Pranab Bordoloi',
    relation: 'Childhood Friend',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    memoryHint: 'Your college roommate at Cotton College (Class of 1970).',
    favoriteMemory: 'Singing Jayanta Hazarika duets at the Cotton College hostel reunion.',
    hometown: 'Jorhat, Assam',
  },
];

export const demoMedications: Medication[] = [
  {
    id: 'med-1',
    name: 'Donepezil (Aricept)',
    dosage: '5 mg tablet',
    timeOfDay: 'night',
    time: '21:00',
    instructions: 'Take 1 tablet before bedtime with a glass of water.',
    takenToday: true,
  },
  {
    id: 'med-2',
    name: 'Memantine HCl',
    dosage: '10 mg tablet',
    timeOfDay: 'morning',
    time: '08:30',
    instructions: 'Take after breakfast with water.',
    takenToday: true,
  },
  {
    id: 'med-3',
    name: 'Telmisartan (Blood Pressure)',
    dosage: '40 mg',
    timeOfDay: 'morning',
    time: '08:30',
    instructions: 'Take once daily in the morning.',
    takenToday: true,
  },
  {
    id: 'med-4',
    name: 'Neurobion Forte (B-Complex)',
    dosage: '1 tablet',
    timeOfDay: 'afternoon',
    time: '13:30',
    instructions: 'Take with warm water after lunch.',
    takenToday: false,
  },
];

export const culturalCards: CulturalCard[] = [
  {
    id: 'cc-1',
    title: {
      as: 'জাপি (Jaapi)',
      bn: 'জাপি (Jaapi)',
      mni: 'Jaapi',
      hi: 'जापी (Jaapi)',
      en: 'Jaapi',
    },
    description: {
      as: 'অসমৰ পৰম্পৰাগত বাঁহ আৰু টকৌ পাতৰ মূৰৰ টুপি। সন্মান আৰু সংস্কৃতিৰ প্ৰতীক।',
      bn: 'আসামের ঐতিহ্যবাহী বাঁশের টুপি, সম্মান ও সংস্কৃতির প্রতীক।',
      mni: 'Assamgi yamna maru oiba kouba jaapi.',
      hi: 'असम की पारंपरिक बांस और ताड़ के पत्तों की टोपी, सम्मान का प्रतीक।',
      en: 'Traditional conical hat made from tightly woven bamboo and palm leaves.',
    },
    icon: '👒',
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'Presented to guests in Assam as a gesture of highest respect.',
  },
  {
    id: 'cc-2',
    title: {
      as: 'শৰাই (Xorai)',
      bn: 'শরাই (Xorai)',
      mni: 'Xorai',
      hi: 'शराई (Xorai)',
      en: 'Xorai',
    },
    description: {
      as: 'কাঁহ-পিতলৰ নৈবেদ্য বা উপহাৰ আগবঢ়োৱা ঐতিহাসিক পাত্ৰ।',
      bn: 'কাঁসার তৈরি ঐতিহ্যবাহী অর্ঘ্য পাত্র।',
      mni: 'Kanh gi thambal matouk oiba pot.',
      hi: 'कांस्य और पीतल का पारंपरिक थाल, पूजा और स्वागत में प्रयुक्त।',
      en: 'Traditional bell-metal offering tray on a stand, manufactured in Sarthebari.',
    },
    icon: '🏆',
    imageUrl: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'Used to present betel nut (Tamul-Paan) and offer prayers at Naamghars.',
  },
  {
    id: 'cc-3',
    title: {
      as: 'গামোচা (Gamusa)',
      bn: 'গামোছা (Gamosa)',
      mni: 'Gamusa',
      hi: 'गमोसा (Gamosa)',
      en: 'Gamosa',
    },
    description: {
      as: 'বগা আৰু ৰঙা সূতাৰে বোৱা অসমীয়া সন্মানৰ কাপোৰ।',
      bn: 'সাদা ও লাল সুতো দিয়ে বোনা অসমীয়া মর্যাদার বস্ত্র।',
      mni: 'Assamgi fajaba khudei machu.',
      hi: 'सफेद और लाल बॉर्डर वाला असमिया सम्मान का पारंपरिक अंगवस्त्र।',
      en: 'Handwoven white rectangular cloth with distinctive red woven borders.',
    },
    icon: '🧣',
    imageUrl: 'https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'Awarded GI tag status; symbolizes love, purity, and veneration of elders.',
  },
  {
    id: 'cc-4',
    title: {
      as: 'ধনেশ পক্ষী (Hornbill)',
      bn: 'ধনেশ পাখি (Hornbill)',
      mni: 'Hornbill Uchek',
      hi: 'हॉर्नबिल पक्षी (Hornbill)',
      en: 'Great Hornbill',
    },
    description: {
      as: 'উত্তৰ-পূৰ্বাঞ্চলৰ পাহাৰৰ গৌৰৱময় বৃহৎ ধনেশ চৰাই।',
      bn: 'উত্তর-পূর্ব ভারতের পাহাড়ের রাজকীয় ধনেশ পাখি।',
      mni: 'Ching gi uchek Hornbill.',
      hi: 'पूर्वोत्तर भारत का विशाल सुंदर पक्षी, नगालैंड का राजकीय प्रतीक।',
      en: 'Majestic bird celebrated across Nagaland and Arunachal Pradesh hill folklore.',
    },
    icon: '🦜',
    imageUrl: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'Celebrated every December in Nagaland during the Hornbill Festival.',
  },
  {
    id: 'cc-5',
    title: {
      as: 'মুগা ৰেচম (Muga Silk)',
      bn: 'মুগা রেশম (Muga Silk)',
      mni: 'Muga Silk',
      hi: 'मूगा सिल्क (Muga Silk)',
      en: 'Golden Muga Silk',
    },
    description: {
      as: 'অসমৰ সোণালী ৰঙৰ প্ৰাকৃতিক ৰেচম, বয়স বাঢ়িলে উজ্বলতা বৃদ্ধি পায়।',
      bn: 'আসামের বিখ্যাত সোনালী রেশম সুতো।',
      mni: 'Sanagi machu manba resham.',
      hi: 'असम का अनूठा प्राकृतिक सुनहरा रेशम जो उम्र के साथ और चमकता है।',
      en: 'Rare golden silk endemic only to Assam, worn during Rongali Bihu dances.',
    },
    icon: '✨',
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'Historically exclusive to Ahom royalty; can last over 100 years.',
  },
  {
    id: 'cc-6',
    title: {
      as: 'বিহু ঢোল (Dhol)',
      bn: 'বিহু ঢোল (Dhol)',
      mni: 'Dholak',
      hi: 'बिहू ढोल (Dhol)',
      en: 'Bihu Dhol',
    },
    description: {
      as: 'কাঠ আৰু চামৰাৰে তৈয়াৰী ৰঙালী বিহুৰ প্ৰধান বাদ্যযন্ত্ৰ।',
      bn: 'বিহু উৎসবের প্রাণ, ঐতিহ্যবাহী ড্রাম বা ঢোল।',
      mni: 'Pung gi makhal ama.',
      hi: 'असमिया बिहू संगीत की धड़कन माना जाने वाला पारंपरिक ढोल।',
      en: 'Two-sided percussion instrument played with bamboo sticks during Bihu.',
    },
    icon: '🥁',
    imageUrl: 'https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'The rhythmic beats simulate the thunderclouds of the spring monsoon.',
  },
  {
    id: 'cc-7',
    title: {
      as: 'মাজুলীৰ মুখা (Majuli Mask)',
      bn: 'মাজুলীর মুখোশ (Majuli Mask)',
      mni: 'Majuli Mask',
      hi: 'माजुली का मुखौटा (Majuli Mask)',
      en: 'Majuli Vaishnavite Mask',
    },
    description: {
      as: 'মাজুলী সত্ৰৰ বাঁহ, মাটি আৰু কাপোৰেৰে নিৰ্মিত ভক্তিমূলক মুখা শিল্প।',
      bn: 'মাজুলী দ্বীপের ঐতিহ্যবাহী হস্তনির্মিত ভক্তিভাবের মুখোশ।',
      mni: 'Majuli gi mask.',
      hi: 'विश्व के सबसे बड़े नदी द्वीप माजुली की पारंपरिक हस्तनिर्मित मुखौटा कला।',
      en: 'Clay and bamboo theatrical masks crafted in Samaguri Satra for Bhaona plays.',
    },
    icon: '🎭',
    imageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'Recent recipient of the prestigious Geographical Indication (GI) tag.',
  },
  {
    id: 'cc-8',
    title: {
      as: 'লোকটক হ্ৰদৰ ফুমদি (Loktak Phumdi)',
      bn: 'লোকটাক হ্রদের ফুমদি (Loktak)',
      mni: 'Loktak Phumdi',
      hi: 'लोकटक झील फुमदी (Loktak)',
      en: 'Floating Phumdis of Loktak',
    },
    description: {
      as: 'মণিপুৰৰ লোকটক হ্ৰদৰ ওপঙি থকা অনন্য জৈৱিক দ্বীপ।',
      bn: 'মণিপুরের লোকটাক হ্রদের ভাসমান অনন্য ফুমদি দ্বীপপুঞ্জ।',
      mni: 'Loktak pat ta yawba phumdi.',
      hi: 'मणिपुर की ताजे पानी की लोकटक झील पर तैरते हुए अद्वितीय प्राकृतिक बायोमास द्वीप।',
      en: 'World’s only floating national park, home to the endangered Sangai dancing deer.',
    },
    icon: '🏞️',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'Keibul Lamjao is the only floating sanctuary of its kind on planet Earth.',
  },
  {
    id: 'cc-9',
    title: {
      as: 'ঢেঁকী (Dheki)',
      bn: 'ঢেঁকি (Dheki)',
      mni: 'Dheki',
      hi: 'ढेंकी (Dheki)',
      en: 'Dheki (Rice Pounder)',
    },
    description: {
      as: 'পৰম্পৰাগত কাঠৰ ধান বনা আৰু পিঠাগুৰি খুন্দা ঐতিহাসিক সঁজুলি।',
      bn: 'ঐতিহ্যবাহী কাঠের তৈরি ধান ও চালের গুঁড়ো বানানোর ঢেঁকি।',
      mni: 'Chempheng saba dheki.',
      hi: 'पारंपरिक लकड़ी का धान कूटने व पिठ्ठा बनाने का यंत्र।',
      en: 'Foot-operated traditional wooden grain pounder used for Bihu pitha preparation.',
    },
    icon: '🌾',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'Central to Bihu festivals across rural North-East households for generations.',
  },
  {
    id: 'cc-10',
    title: {
      as: 'পেঁপা (Pepa)',
      bn: 'পেঁপা (Pepa)',
      mni: 'Pepa Flute',
      hi: 'पेपा बांसुरी (Pepa)',
      en: 'Pepa Horn Flute',
    },
    description: {
      as: 'ম’হৰ শিঙৰে নিৰ্মিত বিহু নৃত্যৰ সুমধুৰ মাঙ্গলিক বাঁহী।',
      bn: 'মহিষের শিং দিয়ে তৈরি বিহু নাচের বাদ্যযন্ত্র।',
      mni: 'Maho machigi khonjel.',
      hi: 'भैंस के सींग से बनी बिहू की पारंपरिक सुरमयी बांसुरी।',
      en: 'Iconic hornpipe crafted from wild buffalo horn and bamboo reed.',
    },
    icon: '🎺',
    imageUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'Only skilled village craftsmen know the secret of curing the buffalo horn for acoustics.',
  },
  {
    id: 'cc-11',
    title: {
      as: 'এশিঙীয়া গঁড় (Rhino)',
      bn: 'একশৃঙ্গ গণ্ডার (Rhino)',
      mni: 'One-horned Rhino',
      hi: 'एक सींग वाला गैंडा',
      en: 'One-Horned Rhinoceros',
    },
    description: {
      as: 'কাজিৰঙাৰ গৌৰৱ আৰু উত্তৰ-পূৰ্বাঞ্চলৰ বিশ্ববিখ্যাত বন্যপ্ৰাণী।',
      bn: 'কাজিরাঙ্গার অহংকার বিশ্ববিখ্যাত একশৃঙ্গ গণ্ডার।',
      mni: 'Kaziranga gi shing ama panba rhino.',
      hi: 'काजीरंगा का गौरव, भारत का प्राचीन एक सींग वाला विशाल गैंडा।',
      en: 'State animal of Assam, thriving in the elephant grass of Kaziranga.',
    },
    icon: '🦏',
    imageUrl: 'https://images.unsplash.com/photo-1575550959106-5a7defe28b56?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'Kaziranga is home to over 2,600 great one-horned rhinos.',
  },
  {
    id: 'cc-12',
    title: {
      as: 'শিপাৰ সঁকো (Living Root Bridge)',
      bn: 'জীবন্ত শিকড়ের সেতু',
      mni: 'Umarol Thong',
      hi: 'जीवंत जड़ों का पुल',
      en: 'Living Root Bridge',
    },
    description: {
      as: 'মেঘালয়ৰ খাচী আৰু জয়ন্তীয়া লোকে গছৰ শিপাৰে গঢ়ি তোলা প্রাকৃতিক সাঁকো।',
      bn: 'মেঘালয়ের খাসি উপজাতির জীবন্ত গাছের শিকড় দিয়ে তৈরি প্রাকৃতিক সেতু।',
      mni: 'Khasi machasingna marolna saba thong.',
      hi: 'मेघालय की खासी जनजातियों द्वारा रबर के पेड़ों की जीवित जड़ों से बुना गया प्राकृतिक पुल।',
      en: 'Bio-engineering wonder created by Khasi and Jaintia tribes over centuries.',
    },
    icon: '🌉',
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=500&q=80',
    culturalFact: 'These living bridges grow stronger and more durable with age.',
  },
  {
    id: 'cc-13',
    title: {
      as: 'মণিপুৰী পুং (Pung)',
      bn: 'মণিপুরী পুং (Pung)',
      mni: 'Meitei Pung',
      hi: 'मणिपुरी पुंग मृदंग',
      en: 'Manipuri Pung Drum',
    },
    description: {
      as: 'মণিপুৰী সংকীৰ্তন আৰু নৃত্যৰ প্ৰাণস্বৰূপ পবিত্ৰ মৃদংগ।',
      bn: 'মণিপুরী সংকীর্তন ও রাস নৃত্যের পবিত্র মৃদঙ্গ বাদ্য।',
      mni: 'Manipuri sankirtan da sijinnaba maru oiba pung.',
      hi: 'मणिपुरी रासलीला व संकीर्तन का आध्यात्मिक पारंपरिक मृदंग।',
      en: 'Soulful barrel drum played during graceful Manipuri classical and folk dances.',
    },
    icon: '🪘',
    culturalFact: 'The Pung Cholom dance combines acrobatic jumps with rhythmic drumming.',
  },
  {
    id: 'cc-14',
    title: {
      as: 'নগা বৰশী আৰু ঢাল (Naga Spear)',
      bn: 'নাগা বর্শা ও ঢাল',
      mni: 'Naga Spear',
      hi: 'नगा भाला व ढाल',
      en: 'Naga Ceremonial Spear & Shield',
    },
    description: {
      as: 'নগাভূমিৰ সাহস আৰু বীৰত্বৰ প্ৰতীক ৰঙীন পাখিৰে সজোৱা বৰশী।',
      bn: 'নাগাল্যান্ডের বীরত্ব ও সংস্কৃতির প্রতীক সুসজ্জিত বর্শা ও ঢাল।',
      mni: 'Naga phuruppi thouna takpa ta.',
      hi: 'नगालैंड की जनजातीय शौर्य और वीरता का अलंकृत पारंपरिक भाला।',
      en: 'Ceremonial spear adorned with dyed goat hair and hand-carved motifs.',
    },
    icon: '🛡️',
    culturalFact: 'Worn with pride during the festive hornbill warrior dances.',
  },
  {
    id: 'cc-15',
    title: {
      as: 'বাঁহ-বেতৰ মূঢ়া (Bamboo Murha)',
      bn: 'বাঁশের তৈরি মোড়া (Murha)',
      mni: 'Wa gi Phamdol',
      hi: 'बांस का पारंपरिक मूढ़ा',
      en: 'Bamboo Cane Stool (Murha)',
    },
    description: {
      as: 'অসমৰ প্ৰতিঘৰৰ চ’ৰাঘৰত আদৰ-সাদৰৰ বাবে ৰখা নিমজ বাঁহৰ আসন।',
      bn: 'ঘরে ঘরে অতিথি আপ্যায়নে ব্যবহৃত ঐতিহ্যবাহী বাঁশ ও বেতের মোড়া।',
      mni: 'Yumda atithi bu amuk henna channa kouba pot.',
      hi: 'पूर्वोत्तर के हर घर में मेहमानों के सत्कार के लिए रखी जाने वाली सुंदर बेंट की बैठक।',
      en: 'Handcrafted eco-friendly bamboo stool central to North-Eastern hospitality.',
    },
    icon: '🪑',
    culturalFact: 'Crafted from sustainable bamboo that matures in just 3 years.',
  },
  {
    id: 'cc-16',
    title: {
      as: 'ত্ৰিপুৰাৰ ৰিগনাই (Tripura Rignai)',
      bn: 'ত্রিপুরার রিগনই (Rignai)',
      mni: 'Tripura Rignai',
      hi: 'त्रिपुरा का रिगनाई वस्त्र',
      en: 'Tripura Traditional Rignai',
    },
    description: {
      as: 'ত্ৰিপুৰাৰ ত্ৰিপুৰী মহিলাসকলে নিজে তাঁতশালত বোৱা চহকী বস্ত্ৰ।',
      bn: 'ত্রিপুরার ঐতিহ্যবাহী হস্তচালিত তাঁতে বোনা রঙিন বস্ত্র।',
      mni: 'Tripura gi nupina saba phanek.',
      hi: 'त्रिपुरा की महिलाओं द्वारा हथकरघे पर बुना जाने वाला सुंदर पारंपरिक परिधान।',
      en: 'Traditional handwoven lower garment with exquisite tribal border motifs.',
    },
    icon: '🥻',
    culturalFact: 'Each clan in Tripura weaves distinct patterns identifying their ancestral lineage.',
  },
  {
    id: 'cc-17',
    title: {
      as: 'টোকাৰী (Tokari Lute)',
      bn: 'টোকারী (Tokari)',
      mni: 'Tokari',
      hi: 'तोकारी तानपुरा (Tokari)',
      en: 'Tokari Folk Lute',
    },
    description: {
      as: 'দেহতত্ত্বৰ গীত আৰু বৈষ্ণৱ নাম-কীৰ্তনত ব্যৱহৃত ঐতিহ্যবাহী তাঁৰৰ বাদ্য।',
      bn: 'বাউল ও ভক্তিমূলক লোকগীতিতে ব্যবহৃত প্রাচীন তারযুক্ত বাদ্যযন্ত্র।',
      mni: 'Shaktigi ishei da sijinnaba pot.',
      hi: 'असमिया लोकगीतों और आध्यात्मिक भजनों में बजने वाला प्राचीन तंत्री वाद्य।',
      en: 'Plucked folk string instrument with a round wooden resonator covered in leather.',
    },
    icon: '🎻',
    culturalFact: 'Played by minstrel storytellers wandering between Brahmaputra villages.',
  },
  {
    id: 'cc-18',
    title: {
      as: 'গগনা (Gogona)',
      bn: 'গগনা (Gogona)',
      mni: 'Gogona',
      hi: 'गगना (Gogona)',
      en: 'Gogona Jaw Harp',
    },
    description: {
      as: 'জাতি বাঁহেৰে সজা ওঁঠত লগাই বজোৱা বিহুৱতীৰ অতি মৰমৰ বাদ্য।',
      bn: 'বাঁশ দিয়ে তৈরি মুখের অভিব্যক্তিতে বাজানো মধুর বিহু বাদ্য।',
      mni: 'Wa na saba chinna khonjel thabagi pot.',
      hi: 'बांस से बनी मुंह से बजाई जाने वाली बिहू की नन्हीं मधुर बांसुरी।',
      en: 'Vibrating bamboo jaw harp played by women dancers during Rongali Bihu.',
    },
    icon: '🎋',
    culturalFact: 'Tucked neatly into the dancer’s hair knot (Khupa) when not playing.',
  },
  {
    id: 'cc-19',
    title: {
      as: 'বড়ো দখনা (Bodo Dokhona)',
      bn: 'বোড়ো দখনা (Dokhona)',
      mni: 'Dokhona',
      hi: 'बोडो दखना (Dokhona)',
      en: 'Bodo Dokhona Weave',
    },
    description: {
      as: 'বড়ো নাৰীসকলৰ হালধীয়া আৰু সোণালী সূতাৰে বোৱা চেনেহৰ পোছাক।',
      bn: 'বোড়ো মহিলাদের নিজস্ব তাঁতে বোনা উজ্জ্বল ঐতিহ্যবাহী হলুদ পোশাক।',
      mni: 'Bodo nupigi fajaba phijol.',
      hi: 'बोडो महिलाओं का चटख पीले रंग का प्रसिद्ध व सुंदर पारंपरिक परिधान।',
      en: 'Brightly colored wrap-around garment handwoven on traditional loin looms.',
    },
    icon: '👘',
    culturalFact: 'Often woven with the "Agor" floral motifs representing nature and rivers.',
  },
  {
    id: 'cc-20',
    title: {
      as: 'চিংলাং ধোঁৱাযুক্ত চাহ (Singphoo Tea)',
      bn: 'সিংফো ঐতিহ্যবাহী বাঁশের চা',
      mni: 'Singphoo Cha',
      hi: 'सिंगफो पारंपरिक बांस की चाय',
      en: 'Traditional Singphoo Tea',
    },
    description: {
      as: 'বাঁহৰ চুঙাত ধোঁৱা দি তৈয়াৰ কৰা উত্তৰ-পূৰ্বাঞ্চলৰ আদিম আৰু প্ৰাকৃতিক চাহ।',
      bn: 'বাঁশের চোঙে ধূমায়িত করে তৈরি আদিম সুগন্ধি ও স্বাস্থ্যকর চা।',
      mni: 'Singphoo phuruppi cha.',
      hi: 'बांस के खंभों में धुएं से पकाई जाने वाली पूर्वोत्तर की प्राचीन औषधीय चाय।',
      en: 'Smoked organic wild tea packed into bamboo cylinders by the Singphoo tribe.',
    },
    icon: '🍵',
    culturalFact: 'The Singphoo people introduced native tea plants to the world in 1823.',
  },
];

export const brainQuestPuzzles: BrainQuestPuzzle[] = [
  // LEVEL 1: Iconic North-East Geography & Wildlife
  {
    id: 'bq-1',
    level: 1,
    question: {
      as: 'কোনখন নদী মাজুলী দ্বীপৰ দুয়োকাষে বৈ গৈছে?',
      bn: 'কোন নদীটি বিশ্বের বৃহত্তম নদী দ্বীপ মাজুলীর পাশ দিয়ে প্রবাহিত?',
      mni: 'Majuli mayada chenba turel karino?',
      hi: 'कौन सी पवित्र और विशाल नदी माजुली द्वीप के चारों ओर बहती है?',
      en: 'Which mighty river flows around the world-famous Majuli island?',
    },
    options: [
      { id: 'o1', label: { as: 'ব্ৰহ্মপুত্ৰ নদী', bn: 'ব্রহ্মপুত্র নদী', mni: 'Brahmaputra Turel', hi: 'ब्रह्मपुत्र नदी', en: 'Brahmaputra River' }, isCorrect: true },
      { id: 'o2', label: { as: 'গঙ্গা নদী', bn: 'গঙ্গা নদী', mni: 'Ganga Turel', hi: 'गंगा नदी', en: 'Ganga River' }, isCorrect: false },
      { id: 'o3', label: { as: 'যমুনা নদী', bn: 'যমুনা নদী', mni: 'Yamuna Turel', hi: 'यमुना नदी', en: 'Yamuna River' }, isCorrect: false },
    ],
    hint: {
      as: 'ইয়াৰ পুৰণি নাম লৌহিত্য বা লুইত।',
      bn: 'এর আরেক নাম লুইত।',
      mni: 'Luit kouba turel.',
      hi: 'इसे असम में प्रेम से "लुइत" भी कहा जाता है।',
      en: 'Also affectionately known across Assam as the "Red River" or "Luit".',
    },
    culturalContext: 'Majuli is surrounded by the mighty Brahmaputra and Kherkutia Xuti.',
  },
  {
    id: 'bq-2',
    level: 1,
    question: {
      as: 'কাজিৰঙা ৰাষ্ট্ৰীয় উদ্যান কিহৰ বাবে বিশ্ববিখ্যাত?',
      bn: 'কাজিরাঙ্গা জাতীয় উদ্যান কোন প্রাণীর জন্য বিশ্ববিখ্যাত?',
      mni: 'Kaziranga da leiba maru oiba sa karino?',
      hi: 'काजीरंगा राष्ट्रीय उद्यान किस दुर्लभ प्राणी के लिए विश्व प्रसिद्ध है?',
      en: 'Kaziranga National Park is globally renowned for which iconic animal?',
    },
    options: [
      { id: 'o1', label: { as: 'এশিঙীয়া গঁড়', bn: 'একশৃঙ্গ গণ্ডার', mni: 'One-horned Rhino', hi: 'एक सींग वाला गैंडा', en: 'One-horned Rhinoceros' }, isCorrect: true },
      { id: 'o2', label: { as: 'বৰফৰ বাঘ (Snow Leopard)', bn: 'তুষার চিতা', mni: 'Snow Leopard', hi: 'हिम तेंदुआ', en: 'Snow Leopard' }, isCorrect: false },
      { id: 'o3', label: { as: 'উট', bn: 'উট', mni: 'Oot', hi: 'ऊंट', en: 'Camel' }, isCorrect: false },
    ],
    hint: {
      as: 'ইয়াৰ নাকৰ ওপৰত মাত্ৰ এটা খৰ্গ থাকে।',
      bn: 'তার নাকের ওপর একটি মাত্র শিং রয়েছে।',
      mni: 'Makhomda machi ama panba sa.',
      hi: 'इसकी नाक पर केवल एक ही शक्तिशाली सींग होता है।',
      en: 'Prehistoric-looking gentle herbivore with a single horn on its snout.',
    },
    culturalContext: 'Kaziranga hosts two-thirds of the world’s great one-horned rhinoceroses.',
  },
  {
    id: 'bq-3',
    level: 1,
    question: {
      as: 'চাহপাত চিঙাৰ সময়ত কোনটো অংশ আটাইতকৈ উৎকৃষ্ট বুলি কোৱা হয়?',
      bn: 'চা পাতা তোলার সময় কোন অংশটি সবচেয়ে উৎকৃষ্ট?',
      mni: 'Cha mana hekpa matamda karamba sakhaye?',
      hi: 'चाय की तुड़ाई करते समय सबसे उत्तम भाग किसे माना जाता है?',
      en: 'Which part of the tea shoot is considered the highest quality pluck?',
    },
    options: [
      { id: 'o1', label: { as: 'দুটি পাত এটি কলি', bn: 'দুটি পাতা একটি কুঁড়ি', mni: 'Mana ani koli ama', hi: 'दो पत्तियां और एक कली', en: 'Two leaves and a bud' }, isCorrect: true },
      { id: 'o2', label: { as: 'পুৰঠ শুকান ডাল', bn: 'শুকনো ডালপালা', mni: 'Akangba marik', hi: 'पुरानी सूखी शाखाएं', en: 'Old dry woody branches' }, isCorrect: false },
      { id: 'o3', label: { as: 'মাটিৰ তলৰ শিপা', bn: 'মাটির নিচের শিকড়', mni: 'Leibakki marol', hi: 'जमीन की जड़ें', en: 'Underground roots' }, isCorrect: false },
    ],
    hint: {
      as: 'সোণালী চাহৰ বিখ্যাত শ্লোগান।',
      bn: 'আসামের বিখ্যাত চা তোলার মূল নিয়ম।',
      mni: 'Cha gi maru oiba rule.',
      hi: 'असम के चाय बागानों का सुप्रसिद्ध मूल मंत्र।',
      en: 'The classic golden harvest rule of Assam tea pluckers.',
    },
    culturalContext: 'Tender two leaves and an unopened terminal bud yield the sweetest liquor.',
  },

  // LEVEL 2: Festivals & Natural Phenomena
  {
    id: 'bq-4',
    level: 2,
    question: {
      as: 'বাপতিসাহোন ৰঙালী বিহু কোন ঋতুত উদ্‌যাপিত হয়?',
      bn: 'রঙালী বিহু কোন ঋতুর আগমনে পালিত হয়?',
      mni: 'Rongali Bihu karamba matamda pangthok-ee?',
      hi: 'उमंग भरा रोंगाली बिहू पर्व किस मौसम के आगमन पर मनाया जाता है?',
      en: 'In which season is the joyous Rongali (Bohag) Bihu celebrated?',
    },
    options: [
      { id: 'o1', label: { as: 'বসন্ত কাল (ব’হাগ)', bn: 'বসন্ত কাল (বৈশাখ)', mni: 'Yenningtha (Spring)', hi: 'वसंत ऋतु (बैसाख)', en: 'Springtime (Bohag)' }, isCorrect: true },
      { id: 'o2', label: { as: 'শীত কাল (পুহ)', bn: 'শীত কাল (পৌষ)', mni: 'Ningthamtha (Winter)', hi: 'शीत ऋतु (सर्दी)', en: 'Mid-Winter' }, isCorrect: false },
      { id: 'o3', label: { as: 'বৰ্ষা কাল (শাওণ)', bn: 'বর্ষা কাল (শ্রাবণ)', mni: 'Nongju (Monsoon)', hi: 'वर्षा ऋतु', en: 'Monsoon' }, isCorrect: false },
    ],
    hint: {
      as: 'কুলি চৰাইৰ মাত আৰু কপৌ ফুল ফুলাৰ সময়।',
      bn: 'কোকিলের ডাক ও অর্কিড ফোটার মরশুম।',
      mni: 'Lei paraba matam.',
      hi: 'जब कोयल गाती है और जंगलों में कपौ फूल (ऑर्किड) खिलते हैं।',
      en: 'The time when cuckoos sing and wild foxtail orchids bloom in the forests.',
    },
    culturalContext: 'Marks the Assamese New Year and the arrival of the spring seeding season.',
  },
  {
    id: 'bq-5',
    level: 2,
    question: {
      as: 'পৃথিৱীৰ একমাত্ৰ ওপঙি থকা হ্ৰদ লোকটক ক’ত অৱস্থিত?',
      bn: 'বিশ্বের একমাত্র ভাসমান লোকটাক হ্রদ কোথায় অবস্থিত?',
      mni: 'Floating Lake Loktak kadaida leibage?',
      hi: 'दुनिया की एकमात्र तैरती हुई लोकटक झील कहाँ स्थित है?',
      en: 'Where is the world’s only floating lake, Loktak Lake, located?',
    },
    options: [
      { id: 'o1', label: { as: 'মণিপুৰত', bn: 'মণিপুরে', mni: 'Manipur da', hi: 'मणिपुर में', en: 'In Manipur' }, isCorrect: true },
      { id: 'o2', label: { as: 'ৰাজস্থানত', bn: 'রাজস্থানে', mni: 'Rajasthan da', hi: 'राजस्थान में', en: 'In Rajasthan' }, isCorrect: false },
      { id: 'o3', label: { as: 'কেৰালাত', bn: 'কেরলে', mni: 'Kerala da', hi: 'केरल में', en: 'In Kerala' }, isCorrect: false },
    ],
    hint: {
      as: 'নাচনী হৰিণা (চাংগাই) পোৱা ঠাই।',
      bn: 'সাংগাই নাচিয়ে হরিণের আবাসভূমি।',
      mni: 'Sangai sa leiba mapham.',
      hi: 'दुर्लभ संगाई नाचने वाले हिरणों का सुंदर गृह।',
      en: 'Home of the rare dancing Sangai deer on Keibul Lamjao.',
    },
    culturalContext: 'Loktak Lake features unique circular floating biomass islands called phumdis.',
  },
  {
    id: 'bq-6',
    level: 2,
    question: {
      as: 'অসমৰ কোনখন ঠাইক ‘ৰেচমৰ মানচেষ্টাৰ’ বা ‘তাঁতৰ নগৰী’ বোলা হয়?',
      bn: 'আসামের কোন শহরকে "রেশমের ম্যাঞ্চেস্টার" বলা হয়?',
      mni: 'Assamgi Reshamgi khubam oiba shaher karino?',
      hi: 'असम के किस ऐतिहासिक नगर को "रेशम का मैनचेस्टर" कहा जाता है?',
      en: 'Which historic weaving town of Assam is famed as the "Manchester of the East"?',
    },
    options: [
      { id: 'o1', label: { as: 'শুৱালকুছি', bn: 'সুয়ালকুচি', mni: 'Sualkuchi', hi: 'सुआलकुची', en: 'Sualkuchi' }, isCorrect: true },
      { id: 'o2', label: { as: 'তেজপুৰ', bn: 'তেজপুর', mni: 'Tezpur', hi: 'तेजपुर', en: 'Tezpur' }, isCorrect: false },
      { id: 'o3', label: { as: 'শিলচৰ', bn: 'শিলচর', mni: 'Silchar', hi: 'सिलचर', en: 'Silchar' }, isCorrect: false },
    ],
    hint: {
      as: 'ব্ৰহ্মপুত্ৰৰ উত্তৰ পাৰৰ তাঁতীসকলৰ প্ৰখ্যাত গাঁও।',
      bn: 'পাট ও মুগা রেশম বুননের প্রধান কেন্দ্র।',
      mni: 'Muga phijol sabe thabak mapham.',
      hi: 'ब्रह्मपुत्र के तट पर स्थित रेशम बुनकरों का विख्यात गांव।',
      en: 'Renowned for handcrafting lustrous golden Muga and Paat silk sarees.',
    },
    culturalContext: 'Nearly every household in Sualkuchi operates a traditional wooden handloom.',
  },

  // LEVEL 3: Traditional Crafts & Ecological Knowledge
  {
    id: 'bq-7',
    level: 3,
    question: {
      as: 'বিহুৰ পেঁপা বাদ্যযন্ত্ৰটো সাধাৰণতে কিহেৰে নিৰ্মাণ কৰা হয়?',
      bn: 'বিহু পেঁপা বাদ্যযন্ত্রটি কী দিয়ে তৈরি করা হয়?',
      mni: 'Pepa flute makhong karina sabe?',
      hi: 'असमिया बिहू की पेपा बांसुरी पारंपरिक रूप से किससे बनाई जाती है?',
      en: 'The traditional Bihu Pepa hornpipe is carved from which material?',
    },
    options: [
      { id: 'o1', label: { as: 'ম’হৰ শিং আৰু বাঁহ', bn: 'মহিষের শিং ও বাঁশ', mni: 'Maho machi wa', hi: 'भैंस का सींग व बांस', en: 'Buffalo horn & bamboo' }, isCorrect: true },
      { id: 'o2', label: { as: 'লোহা আৰু তাম', bn: 'লোহা ও তামা', mni: 'Yot amasung tam', hi: 'लोहा और तांबा', en: 'Iron & copper' }, isCorrect: false },
      { id: 'o3', label: { as: 'প্লাষ্টিক পাইপ', bn: 'প্লাস্টিক পাইপ', mni: 'Plastic pipe', hi: 'प्लास्टिक पाइप', en: 'Plastic pipe' }, isCorrect: false },
    ],
    hint: {
      as: 'পথাৰত চৰি থকা ম’হৰ শিঙৰ প্ৰাকৃতিক খোৰোং।',
      bn: 'মহিষের শক্ত মজবুত শিং।',
      mni: 'Maho gi machi.',
      hi: 'पालतू जंगली भैंस के प्राकृतिक मजबूत सींग।',
      en: 'Crafted from wild Asian water buffalo horns naturally collected by craftsmen.',
    },
    culturalContext: 'The buffalo horn is seasoned in smoke above the kitchen hearth for months.',
  },
  {
    id: 'bq-8',
    level: 3,
    question: {
      as: 'মেঘালয়ৰ বিশ্ববিখ্যাত জীৱন্ত শিপাৰ দলং কোনবিধ গছৰ শিপাৰে গঢ়া হয়?',
      bn: 'মেঘালয়ের জীবন্ত শিকড়ের সেতু কোন গাছের শিকড় দিয়ে তৈরি হয়?',
      mni: 'Living Root Bridge karamba u gi marolna saba?',
      hi: 'मेघालय का विश्वप्रसिद्ध जीवित जड़ों का पुल किस पेड़ की जड़ों से बनाया जाता है?',
      en: 'Meghalaya’s Living Root Bridges are woven from the aerial roots of which tree?',
    },
    options: [
      { id: 'o1', label: { as: 'ৰবৰ গছ (Ficus elastica)', bn: 'রবার গাছ (Ficus elastica)', mni: 'Rubber U (Ficus)', hi: 'भारतीय रबर का पेड़ (Ficus)', en: 'Indian Rubber Fig (Ficus)' }, isCorrect: true },
      { id: 'o2', label: { as: 'আম গছ', bn: 'আম গাছ', mni: 'Heinou U', hi: 'आम का पेड़', en: 'Mango tree' }, isCorrect: false },
      { id: 'o3', label: { as: 'নাৰিকল গছ', bn: 'নারকেল গাছ', mni: 'Yubi U', hi: 'नारियल का पेड़', en: 'Coconut palm' }, isCorrect: false },
    ],
    hint: {
      as: 'ইয়াৰ দীঘলীয়া আৰু নমনীয় শক্তিশালী বায়বীয় শিপা থাকে।',
      bn: 'শক্তিশালী নমনীয় ঝুড়ি নামা রবার ডাল।',
      mni: 'Marol thuna thokpa u.',
      hi: 'इसकी लंबी हवाई जड़ें नदी के आर-पार बांस के सहारे बांधी जाती हैं।',
      en: 'Produces resilient flexible aerial roots guided through hollow betel trunks.',
    },
    culturalContext: 'Khasi tribes train the living roots over decades, creating bridges that last centuries.',
  },
  {
    id: 'bq-9',
    level: 3,
    question: {
      as: 'প্ৰতি বছৰে ডিচেম্বৰ মাহত বিশ্ববিখ্যাত হৰ্ণবিল মহোৎসৱ ক’ত অনুষ্ঠিত হয়?',
      bn: 'প্রতি বছর ডিসেম্বরে বিখ্যাত হর্নবিল উৎসব কোথায় অনুষ্ঠিত হয়?',
      mni: 'Hornbill Festival karamba state ta pangthok-ee?',
      hi: 'हर वर्ष दिसंबर में विश्वप्रसिद्ध हॉर्नबिल उत्सव किस राज्य में मनाया जाता है?',
      en: 'In which state is the renowned annual Hornbill Festival celebrated each December?',
    },
    options: [
      { id: 'o1', label: { as: 'নাগালেণ্ডত (কিসামা)', bn: 'নাগাল্যান্ডে (কিসামা)', mni: 'Nagaland da (Kisama)', hi: 'नागालैंड में (किसामा)', en: 'In Nagaland (Kisama)' }, isCorrect: true },
      { id: 'o2', label: { as: 'পাঞ্জাবত', bn: 'পাঞ্জাবে', mni: 'Punjab da', hi: 'पंजाब में', en: 'In Punjab' }, isCorrect: false },
      { id: 'o3', label: { as: 'গুজৰাটত', bn: 'গুজরাটে', mni: 'Gujarat da', hi: 'गुजरात में', en: 'In Gujarat' }, isCorrect: false },
    ],
    hint: {
      as: '১৬টা নগা জনজাতিৰ একতাৰ মহা-মিলনমেলা।',
      bn: 'নাগা পাহাড়ের বর্ণাঢ্য উপজাতীয় মিলনমেলা।',
      mni: 'Naga furup mayamgi thouram.',
      hi: 'नगालैंड की सभी प्रमुख जनजातियों का रंगारंग सांस्कृतिक महाकुंभ।',
      en: 'Famed as the "Festival of Festivals", uniting all 16 Naga cultural tribes.',
    },
    culturalContext: 'Named after the sacred Great Hornbill bird deeply revered in Naga folklore.',
  },

  // LEVEL 4: Architecture, Topography & Heritage
  {
    id: 'bq-10',
    level: 4,
    question: {
      as: 'আহোম স্বৰ্গদেউসকলে সাজি উলিওৱা এছিয়াৰ প্ৰাচীনতম দুইমহলীয়া ৰংঘৰ ক’ত অৱস্থিত?',
      bn: 'আহোম রাজাদের তৈরি এশিয়ার প্রাচীনতম দোতলা রংঘর কোথায় অবস্থিত?',
      mni: 'Ahom ningthou singna saba Rang Ghar kadaida leibage?',
      hi: 'अहोम राजाओं द्वारा निर्मित एशिया का सबसे प्राचीन रंगमंच (रंग घर) कहाँ स्थित है?',
      en: 'Where is Asia’s oldest two-storey royal sporting pavilion, Rang Ghar, located?',
    },
    options: [
      { id: 'o1', label: { as: 'শিৱসাগৰত', bn: 'শিবসাগরে', mni: 'Sivasagar da', hi: 'शिवसागर में', en: 'In Sivasagar' }, isCorrect: true },
      { id: 'o2', label: { as: 'কোলকাতাত', bn: 'কলকাতায়', mni: 'Kolkata da', hi: 'कोलकाता में', en: 'In Kolkata' }, isCorrect: false },
      { id: 'o3', label: { as: 'দিল্লীত', bn: 'দিল্লিতে', mni: 'Delhi da', hi: 'दिल्ली में', en: 'In Delhi' }, isCorrect: false },
    ],
    hint: {
      as: 'ঐতিহাসিক ৰুদ্ৰসাগৰ আৰু জয়সাগৰৰ আহোম ৰাজধানী নগৰী।',
      bn: 'ঐতিহাসিক আহোম সাম্রাজ্যের প্রধান রাজধানী।',
      mni: 'Ahom ningthougi mayol shaher.',
      hi: 'अहोम साम्राज्य की ऐतिहासिक राजधानी जहां तालाब और प्राचीन मंदिर हैं।',
      en: 'Historic royal seat built under King Pramatta Singha in 1744.',
    },
    culturalContext: 'Used by Ahom royalty as an open-air amphitheater to watch buffalo and bird fights.',
  },
  {
    id: 'bq-11',
    level: 4,
    question: {
      as: 'ব্ৰহ্মপুত্ৰৰ বুকুত থকা পৃথিৱীৰ আটাইতকৈ সৰু জনবসতিপূৰ্ণ নদীদ্বীপটোৰ নাম কি?',
      bn: 'ব্রহ্মপুত্রের বুকে অবস্থিত পৃথিবীর ক্ষুদ্রতম জনবসতিপূর্ণ নদীদ্বীপের নাম কী?',
      mni: 'Prithibigi khwaina pikpa river island karino?',
      hi: 'ब्रह्मपुत्र नदी के मध्य स्थित विश्व के सबसे छोटे आबाद नदी द्वीप का क्या नाम है?',
      en: 'What is the name of the world’s smallest inhabited river island in the Brahmaputra?',
    },
    options: [
      { id: 'o1', label: { as: 'উমানন্দ দ্বীপ (Peacock Island)', bn: 'উমানন্দ দ্বীপ (Peacock Island)', mni: 'Umananda Island', hi: 'उमानंद द्वीप (पीकॉक द्वीप)', en: 'Umananda (Peacock Island)' }, isCorrect: true },
      { id: 'o2', label: { as: 'আন্দামান দ্বীপ', bn: 'আন্দামান দ্বীপ', mni: 'Andaman', hi: 'अंडमान द्वीप', en: 'Andaman Island' }, isCorrect: false },
      { id: 'o3', label: { as: 'লাক্ষাদ্বীপ', bn: 'লাক্ষাদ্বীপ', mni: 'Lakshadweep', hi: 'लक्षद्वीप', en: 'Lakshadweep' }, isCorrect: false },
    ],
    hint: {
      as: 'গুৱাহাটীৰ ঘাটৰ সমুখত থকা শিৱ মন্দিৰৰ দ্বীপ।',
      bn: 'গুয়াহাটির সামনে ময়ূর আকৃতির সুন্দর শিবদ্বীপ।',
      mni: 'Guwahati mayada leiba Shiva laisanggi island.',
      hi: 'गुवाहाटी के सम्मुख ब्रह्मपुत्र में स्थित सुरम्य शिव मंदिर द्वीप।',
      en: 'Peacock-shaped rocky islet home to the Golden Langur and Lord Shiva shrine.',
    },
    culturalContext: 'British officers called it Peacock Island due to its scenic avian shape.',
  },
  {
    id: 'bq-12',
    level: 4,
    question: {
      as: 'মিজোৰামৰ সুপ্ৰসিদ্ধ বাঁহৰ নৃত্যৰ প্ৰাচীন পৰম্পৰাগত নাম কি?',
      bn: 'মিজোরামের বিশ্বখ্যাত বাঁশের নৃত্যের ঐতিহ্যবাহী নাম কী?',
      mni: 'Mizoram gi Wa jagoi gi maming karino?',
      hi: 'मिजोरम के प्रसिद्ध बांस नृत्य का पारंपरिक नाम क्या है?',
      en: 'What is the traditional name of Mizoram’s globally acclaimed bamboo dance?',
    },
    options: [
      { id: 'o1', label: { as: 'চেৰাও নৃত্য (Cheraw)', bn: 'চেরাও নৃত্য (Cheraw)', mni: 'Cheraw Jagoi', hi: 'चेराव नृत्य (Cheraw)', en: 'Cheraw Dance' }, isCorrect: true },
      { id: 'o2', label: { as: 'ভাংৰা', bn: 'ভাংড়া', mni: 'Bhangra', hi: 'भांगड़ा', en: 'Bhangra' }, isCorrect: false },
      { id: 'o3', label: { as: 'গৰবা', bn: 'গরবা', mni: 'Garba', hi: 'गरबा', en: 'Garba' }, isCorrect: false },
    ],
    hint: {
      as: 'চাৰিযোৰ বাঁহৰ ছন্দময় তালত খোজ দি নচা নৃত্য।',
      bn: 'সমান্তরাল বাঁশের তালে তালে পা ফেলে দ্রুত নৃত্য।',
      mni: 'Wa pareng da nupina khong chepna jagoi saba.',
      hi: 'जमीन पर रखे बांसों की तालबद्ध खनक के बीच नर्तकियां फुर्ती से कदम रखती हैं।',
      en: 'Performed by stepping skillfully between rhythmic clapping bamboo staves.',
    },
    culturalContext: 'Dating back to the 1st century AD, it is performed during Chapchar Kut harvest.',
  },

  // LEVEL 5: Indigenous Wisdom Folk Riddles (ডাঁৰৰ সাঁথৰ)
  {
    id: 'bq-13',
    level: 5,
    question: {
      as: 'লোক সাঁথৰ: "ৰাতি ফুৰে দিনে শুৱে, চকু নাই অথচ কান্দে — ই কি বস্তু?"',
      bn: 'লোক ধাঁধা: "রাতে ঘোরে দিনে ঘুমায়, চোখ নেই তবুও কাঁদে — এটি কী?"',
      mni: 'Folk Riddle: "Ahingda chatli, nungthilda tumli, mityeng yaodraba marol pirang tarak-ee — Karino?"',
      hi: 'पूर्वोत्तर लोक पहेली: "रात में घूमे, दिन में सोए, आंख नहीं पर जल बरसाए — यह क्या है?"',
      en: 'Hill Folk Riddle: "Wanders by night, sleeps by dawn, has no eyes yet weeps gently across the hills — what is it?"',
    },
    options: [
      { id: 'o1', label: { as: 'মেঘ বা কুঁৱলী', bn: 'মেঘ বা শিশির', mni: 'Leichil / Irik (Cloud/Dew)', hi: 'मेघ / बादल या ओस', en: 'Cloud or Morning Dew' }, isCorrect: true },
      { id: 'o2', label: { as: 'শিলগুটি', bn: 'পাথরের টুকরো', mni: 'Nungkhok', hi: 'पत्थर का टुकड़ा', en: 'River pebble' }, isCorrect: false },
      { id: 'o3', label: { as: 'বাঁহৰ লাঠি', bn: 'বাঁশের লাঠি', mni: 'Wa chei', hi: 'बांस का डंडा', en: 'Bamboo cane' }, isCorrect: false },
    ],
    hint: {
      as: 'আকাশৰ পৰা টোপাল হৈ খহি পৰে।',
      bn: 'আকাশ থেকে বৃষ্টি হয়ে ঝরে।',
      mni: 'Nong oina tari.',
      hi: 'यह आसमान से बारिश बनकर पहाड़ों पर बरसता है।',
      en: 'Condensed water vapors that blanket the tea hills at daybreak.',
    },
    culturalContext: 'Traditional Assamese elder riddle passed through oral folktales by hearths.',
  },
  {
    id: 'bq-14',
    level: 5,
    question: {
      as: 'লোক সাঁথৰ: "তিনি ঠেঙৰ ঘোঁৰা, পিঠিত বহে বুঢ়া — কাণত ধৰি টানিলে দিলে ডাঙৰ দৌৰ — ই কি বস্তু?"',
      bn: 'লোক ধাঁধা: "তিন পায়ের ঘোড়া, পিঠে বসে বুড়ো — এটি কীসের সংকেত?"',
      mni: 'Folk Riddle: "Khong ahum panba sagol — Dheki gi wahan karino?"',
      hi: 'लोक पहेली: "तीन पाँव का अनोखा घोड़ा, जिस पर पाँव रखकर दबाने से धान कूटा जाए — यह क्या है?"',
      en: 'Folk Riddle: "A three-legged wooden steed that doesn’t run, but stamps rhythmically when stepped on — what is it?"',
    },
    options: [
      { id: 'o1', label: { as: 'ঢেঁকী (ধান বনা সঁজুলি)', bn: 'ঢেঁকি (চাল ভাঙার যন্ত্র)', mni: 'Dheki', hi: 'ढेंकी (धान कूटने का लकड़ी का यंत्र)', en: 'Dheki (Traditional Wooden Pounder)' }, isCorrect: true },
      { id: 'o2', label: { as: 'মটৰ চাইকেল', bn: 'মোটরসাইকেল', mni: 'Motorcycle', hi: 'मोटरसाइकिल', en: 'Motorcycle' }, isCorrect: false },
      { id: 'o3', label: { as: 'ট্ৰেক্টৰ', bn: 'ট্র্যাক্টর', mni: 'Tractor', hi: 'ट्रैक्टर', en: 'Farm Tractor' }, isCorrect: false },
    ],
    hint: {
      as: 'বিহুৰ সময়ত পিঠাগুৰি খুন্দা গাঁৱৰ কাঠৰ ডাঙৰ যন্ত্ৰ।',
      bn: 'ধান ও চালের গুঁড়ো তৈরির কাঠের ঐতিহ্যবাহী যন্ত্র।',
      mni: 'Chempheng saba pot.',
      hi: 'गाँव में बुजुर्ग महिलाएं पैर के सहारे लकड़ी के लीवर को दबाकर धान कूटती हैं।',
      en: 'Traditional lever-beam wooden apparatus in Assamese backyards.',
    },
    culturalContext: 'Featured across folklore as the beloved wooden heart of the rural Assamese homestead.',
  },
  {
    id: 'bq-15',
    level: 5,
    question: {
      as: 'লোক সাঁথৰ: "এহাতে খাপ খাই, মূৰত ল’লে ছাঁ দিয়ে, বৰষুণেও নতিতায় — ই কি বস্তু?"',
      bn: 'লোক ধাঁধা: "মাথায় দিলে ছায়া দেয়, রোদে-জলে গা বাঁচায় — ঐতিহ্যবাহী এটি কী?"',
      mni: 'Folk Riddle: "Kok ta yeingbada numit nong amatta thengnade — Karino?"',
      hi: 'लोक पहेली: "सिर पर रखो तो धूप व बारिश भगाए, बांस व तोकौ पत्तों से बना — यह क्या है?"',
      en: 'Folk Riddle: "Conical crown of woven bamboo and Tokou palm leaves that shelters farmers from blazing sun and rain — what is it?"',
    },
    options: [
      { id: 'o1', label: { as: 'জাপি (Japi)', bn: 'জাপি (Japi)', mni: 'Japi Hat', hi: 'जापी (Japi पारंपरिक टोपी)', en: 'Japi (Conical Bamboo Hat)' }, isCorrect: true },
      { id: 'o2', label: { as: 'লোহাৰ হেলমেট', bn: 'লোহার হেলমেট', mni: 'Helmet', hi: 'लोहे का हेलमेट', en: 'Iron helmet' }, isCorrect: false },
      { id: 'o3', label: { as: 'কাগজৰ টুপী', bn: 'কাগজের টুপি', mni: 'Paper cap', hi: 'कागज की टोपी', en: 'Paper cap' }, isCorrect: false },
    ],
    hint: {
      as: 'খেতিয়কে মূৰত পিন্ধা আৰু আলহীক সন্মান জনোৱা অসমীয়া প্ৰতীক।',
      bn: 'আসামের চিরন্তন শ্রদ্ধার প্রতীক ও কৃষকের রক্ষাকবচ।',
      mni: 'Assamgi maru oiba japi.',
      hi: 'असमिया किसानों का धूप का छत्र और स्वागत में भेंट किया जाने वाला सम्मान प्रतीक।',
      en: 'Conical sunhat hand-woven from Tokou palm fronds and bamboo strips.',
    },
    culturalContext: 'Used by field workers (Haluwa Japi) and presented with red-velvet borders as an honor (Phulam Japi).',
  },
];

export const routineCards: RoutineCard[] = [
  {
    id: 'rc-1',
    title: {
      as: 'পুৱাৰ গৰম চাহ আৰু বিস্কুট',
      bn: 'সকালের গরম চা ও বিস্কুট',
      mni: 'Ayangba Cha thakpa',
      hi: 'सुबह की गर्मागर्म असमिया चाय',
      en: 'Morning Hot Assam Tea',
    },
    icon: '☕',
    correctOrder: 1,
    timeLabel: '07:00 AM',
    period: 'morning',
  },
  {
    id: 'rc-2',
    title: {
      as: 'ফুলনিত খোজকঢ়া আৰু ফুল চোৱা',
      bn: 'বাগানে সকালের হাঁটা ও ফুল দেখা',
      mni: 'Garden da leibak chatpa',
      hi: 'बगीचे में सुबह की ताजी सैर',
      en: 'Garden Stroll & Watering Orchids',
    },
    icon: '🌸',
    correctOrder: 2,
    timeLabel: '08:00 AM',
    period: 'morning',
  },
  {
    id: 'rc-3',
    title: {
      as: 'পুৱাৰ ঔষধ আৰু স্বাস্থ্যকৰ জলপান',
      bn: 'সকালের ওষুধ ও প্রাতরাশ',
      mni: 'Ayangba hidak chaba',
      hi: 'सुबह की दवाइयां व नाश्ता',
      en: 'Morning Medicines & Breakfast',
    },
    icon: '💊',
    correctOrder: 3,
    timeLabel: '08:45 AM',
    period: 'morning',
  },
  {
    id: 'rc-4',
    title: {
      as: 'নামঘৰত চাকি জ্বলোৱা বা প্ৰাৰ্থনা',
      bn: 'পূজাপাঠ ও প্রার্থনা করা',
      mni: 'Laining Laisang chatpa',
      hi: 'नामघर में दीया जलाना व शांत प्रार्थना',
      en: 'Quiet Prayer at Naamghar / Puja Altar',
    },
    icon: '🪔',
    correctOrder: 4,
    timeLabel: '10:30 AM',
    period: 'morning',
  },
  {
    id: 'rc-5',
    title: {
      as: 'দুপৰীয়াৰ গৰম ভাত আৰু ডালি',
      bn: 'দুপুরের খাবার ও বিশ্রাম',
      mni: 'Nungthilgi chak chaba',
      hi: 'दोपहर का भोजन और हल्का विश्राम',
      en: 'Afternoon Lunch & Gentle Nap',
    },
    icon: '🍛',
    correctOrder: 5,
    timeLabel: '01:30 PM',
    period: 'afternoon',
  },
  {
    id: 'rc-6',
    title: {
      as: 'দুপৰীয়াৰ বিশ্ৰাম আৰু কিতাপ পঢ়া',
      bn: 'দুপুরের বিশ্রাম ও বই পড়া',
      mni: 'Nungthil pottha-nungai',
      hi: 'दोपहर का विश्राम और पुस्तक पाठ',
      en: 'Afternoon Rest & Reading',
    },
    icon: '📖',
    correctOrder: 6,
    timeLabel: '03:00 PM',
    period: 'afternoon',
  },
  {
    id: 'rc-7',
    title: {
      as: 'পদূলিমুখত বতাহ লোৱা আৰু ফুল চোৱা',
      bn: 'উঠোনে সান্ধ্য হাওয়া ও হাঁটাহাঁটি',
      mni: 'Yumsumda chatpa',
      hi: 'आंगन में ताजी हवा व टहलना',
      en: 'Courtyard Walk & Evening Breeze',
    },
    icon: '🌿',
    correctOrder: 7,
    timeLabel: '05:00 PM',
    period: 'evening',
  },
  {
    id: 'rc-8',
    title: {
      as: 'সন্ধিয়াৰ বাতৰি আৰু পৰিয়ালৰ সৈতে কথা',
      bn: 'সন্ধ্যার আড্ডা ও পরিবারের সান্নিধ্য',
      mni: 'Numidang Imunggi mi kayaga wari saba',
      hi: 'शाम की चाय और परिजनों से बातचीत',
      en: 'Evening Tea & Family Conversation',
    },
    icon: '🌅',
    correctOrder: 8,
    timeLabel: '06:30 PM',
    period: 'evening',
  },
  {
    id: 'rc-9',
    title: {
      as: 'পৰিয়ালৰ সৈতে নিশাৰ তৃপ্তিদায়ক আহাৰ',
      bn: 'পরিবারের সঙ্গে রাতের তৃপ্তিকর আহার',
      mni: 'Imunggi meeyoi kayaga chak chaba',
      hi: 'परिवार के साथ रात्रि का भोजन',
      en: 'Night Dinner with Loved Ones',
    },
    icon: '🍲',
    correctOrder: 9,
    timeLabel: '08:30 PM',
    period: 'night',
  },
  {
    id: 'rc-10',
    title: {
      as: 'নিশাৰ নিয়মীয়া ঔষধ আৰু এঘটি পানী',
      bn: 'রাতের নিয়মিত ওষুধ ও জলপান',
      mni: 'Numidang hidak chaba',
      hi: 'रात की नियमित दवाइयां व पानी',
      en: 'Bedtime Medicines & Hydration',
    },
    icon: '🥛',
    correctOrder: 10,
    timeLabel: '09:30 PM',
    period: 'night',
  },
  {
    id: 'rc-11',
    title: {
      as: 'ঈশ্বৰ স্মৰণ আৰু শান্তিৰে নিদ্ৰা',
      bn: 'শান্তিপূর্ণ প্রার্থনা ও নিশ্চিন্ত ঘুম',
      mni: 'Laining thouni amsung gumba',
      hi: 'ईश्वर स्मरण और शांतिपूर्ण विश्राम',
      en: 'Night Prayer & Restful Sleep',
    },
    icon: '🌙',
    correctOrder: 11,
    timeLabel: '10:00 PM',
    period: 'night',
  },
];

export const soundCards: SoundCard[] = [
  {
    id: 'sc-1',
    title: {
      as: 'বিহু পেঁপাৰ সুৰ',
      bn: 'বিহু পেঁপার সুর',
      mni: 'Pepa Khonjel',
      hi: 'बिहू पेपा की सुरीली धुन',
      en: 'Bihu Buffalo Horn Flute (Pepa)',
    },
    soundType: 'pepa_flute',
    icon: '🎺',
    description: {
      as: 'ম’হৰ শিঙৰ পেঁপাৰ গুঞ্জৰিত মন জুৰোৱা বিহুৰ মাঙ্গলিক ধ্বনি।',
      bn: 'মহিষের শিং দিয়ে তৈরি ঐতিহ্যবাহী পেঁপার মিষ্টি সুর।',
      mni: 'Maho machi gi pepa khonjel.',
      hi: 'भैंस के सींग से बनी पेपा की मनमोहक सुरमयी धुन।',
      en: 'Resonant folk reed instrument made from indigenous buffalo horn.',
    },
  },
  {
    id: 'sc-2',
    title: {
      as: 'কামাখ্যা মন্দিৰৰ কাঁহৰ ঘণ্টা',
      bn: 'কামাখ্যা মন্দিরের কাঁসার ঘণ্টা',
      mni: 'Laisang gi thabi khonjel',
      hi: 'कामाख्या मंदिर की दिव्य घंटी',
      en: 'Sacred Kamakhya Temple Bell',
    },
    soundType: 'temple_bell',
    icon: '🔔',
    description: {
      as: 'নীলাচল পাহাৰৰ পবিত্ৰ মন্দিৰৰ শান্তিময় ঘণ্টাৰ গভীৰ ধ্বনি।',
      bn: 'নীলাচল পাহাড়ের মন্দিরের গম্ভীর শান্তিময় ঘণ্টাধ্বনি।',
      mni: 'Laisang gi fajaba khonjel.',
      hi: 'नीलाचल पर्वत पर स्थित पावन मंदिर की शांत आध्यात्मिक अनुगूंज।',
      en: 'Deep harmonic bronze bell chime from Nilachal Hills overlooking Guwahati.',
    },
  },
  {
    id: 'sc-3',
    title: {
      as: 'চেৰাপুঞ্জীৰ বৰষুণৰ শব্দ',
      bn: 'চেরাপুঞ্জির মধুর বৃষ্টির ধারা',
      mni: 'Cherapunji gi nong khonjel',
      hi: 'चेरापूंजी की सुकून भरी बारिश',
      en: 'Cherrapunji Monsoon Showers',
    },
    soundType: 'monsoon_rain',
    icon: '🌧️',
    description: {
      as: 'মেঘালয়ৰ পাহাৰৰ সুকোমল সজীৱ বাৰিষাৰ টোপালৰ ছন্দ।',
      bn: 'মেঘালয়ের সবুজ পাহাড়ে নরম বৃষ্টির কোমল ছন্দ।',
      mni: 'Chingda taraba nong khonjel.',
      hi: 'मेघालय की हरी-भरी पहाड़ियों पर गिरती बूंदों का शांत संगीत।',
      en: 'Gentle, meditative rhythm of rainfall amidst the clouds of Meghalaya.',
    },
  },
  {
    id: 'sc-4',
    title: {
      as: 'লোকটক হ্ৰদৰ পানীৰ লহৰ',
      bn: 'লোকটাক হ্রদের মৃদু জলের শব্দ',
      mni: 'Loktak pat ki ishing khonjel',
      hi: 'लोकटक झील की शांत लहरें',
      en: 'Loktak Lake Gentle Ripples',
    },
    soundType: 'lake_ripples',
    icon: '🚣',
    description: {
      as: 'মণিপুৰৰ লোকটক হ্ৰদত নাও চলোৱাৰ সময়ৰ শান্ত ঢৌৰ শব্দ।',
      bn: 'লোকটাক হ্রদে নৌকা চলার সময়ের স্নিগ্ধ জলের মৃদু শব্দ।',
      mni: 'Hi houba matamda thokpa ishing khonjel.',
      hi: 'मणिपुर की लोकटक झील में नौका विहार करते समय उठती कोमल जलतरंगें।',
      en: 'Soothing lap of clear water against traditional wooden fishing canoes.',
    },
  },
  {
    id: 'sc-5',
    title: {
      as: 'ধনেশ পক্ষীৰ বননিৰ মাত',
      bn: 'ধনেশ পাখির অরণ্যের ডাক',
      mni: 'Hornbill uchek gi khonjel',
      hi: 'ग्रेट हॉर्नबिल पक्षी की गूंज',
      en: 'Great Hornbill Canopy Call',
    },
    soundType: 'hornbill_call',
    icon: '🌲',
    description: {
      as: 'নগাভূমি আৰু অৰুণাচলৰ গভীৰ অৰণ্যৰ ৰাজকীয় পক্ষীৰ আহ্বান।',
      bn: 'অরুণাচলের গভীর সবুজ বনের ধনেশ পাখির গম্ভীর ডাক।',
      mni: 'Umunggi uchek khonjel.',
      hi: 'पूर्वोत्तर के घने वर्षावनों के वितान में गूंजती हॉर्नबिल की आवाज।',
      en: 'Resonant low canopy call echoing across the rainforest valleys.',
    },
  },
  {
    id: 'sc-6',
    title: {
      as: 'বিহু ঢোলৰ উদ্দীপক তাল',
      bn: 'বিহু ঢোলের প্রাণবন্ত ছন্দ',
      mni: 'Bihu Dhol gi khonjel',
      hi: 'बिहू ढोल की उमंग भरी थाप',
      en: 'Rousing Bihu Dhol Beats',
    },
    soundType: 'bihu_dhol',
    icon: '🥁',
    description: {
      as: 'বসন্ত উৎসৱ আৰু ৰঙালী বিহুৰ প্ৰাণস্পন্দন সৃষ্টিকাৰী ঢোলৰ গুৰু গম্ভীৰ মাত।',
      bn: 'আসামের বসন্ত উৎসব ও বিহু নৃত্যের প্রাণবন্ত ঢোলের তাল।',
      mni: 'Bihu kumhei gi dhol maru oiba khonjel.',
      hi: 'असमिया नववर्ष व बिहू नृत्य की हृदयस्पर्शी पारंपरिक ढोल की थाप।',
      en: 'Heart-pumping traditional folk drum rhythm marking Spring Bihu celebration.',
    },
  },
  {
    id: 'sc-7',
    title: {
      as: 'পাহাৰী নিজৰাৰ কুলু কুলু সোঁত',
      bn: 'পাহাড়ি ঝর্ণার মধুর কলতান',
      mni: 'Chinggi turel macha khonjel',
      hi: 'पहाड़ी झरने की निर्मल कल-कल धारा',
      en: 'Gentle Mountain Stream Flow',
    },
    soundType: 'stream_water',
    icon: '🌊',
    description: {
      as: 'অসম আৰু অৰুণাচলৰ সেউজ পাহাৰৰ বুকুত বৈ অহা সতেজ জুৰিৰ পানীৰ ছন্দ।',
      bn: 'সবুজ পাহাড়ের বুক চিরে বয়ে চলা স্নিগ্ধ পাহাড়ি ঝর্ণার মধুর আওয়াজ।',
      mni: 'Chinggi turel gi nungshiba khonjel.',
      hi: 'पूर्वोत्तर की हरी-भरी वादियों में कल-कल बहते शांत प्राकृतिक सोते का स्वर।',
      en: 'Pure crystal waters flowing over smooth pebbles in pristine Eastern Himalayas.',
    },
  },
  {
    id: 'sc-8',
    title: {
      as: 'নামঘৰৰ মাঙ্গলিক শংখধ্বনি',
      bn: 'সন্ধ্যার শুভ শাঁখের পবিত্র ধ্বনি',
      mni: 'Laisang da khonjel thokpa Khongkhang',
      hi: 'संध्याकालीन पावन मंगल शंख ध्वनि',
      en: 'Auspicious Evening Conch (Shankha)',
    },
    soundType: 'conch_shell',
    icon: '🐚',
    description: {
      as: 'সন্ধিয়া নামঘৰ আৰু মন্দিৰৰ শান্তিময় পৱিত্ৰ মংগলধ্বনি।',
      bn: 'সন্ধ্যা আরতিতে বেজে ওঠা মন শান্ত করা শুভ শঙ্খনাদ।',
      mni: 'Laisang gi santhiba thouni khongkhang.',
      hi: 'मंदिरों व नामघरों में संध्या बेला में गूंजने वाला मंगलकारी पावन शंखनाद।',
      en: 'Sacred resonance of evening conch shell echoing peace and serenity.',
    },
  },
];

// 30-day realistic longitudinal history for Recharts graphs
export const demoCognitiveHistory: CognitiveSession[] = Array.from({ length: 30 }).map((_, i) => {
  const d = new Date();
  d.setDate(d.getDate() - (29 - i));
  const dateStr = d.toISOString().split('T')[0];

  const domains: CognitiveSession['domain'][] = [
    'visual_spatial',
    'attention_motor',
    'executive_function',
    'pattern_logic',
    'temporal_orientation',
    'auditory_memory',
    'autobiographical',
  ];

  const domain = domains[i % domains.length];
  // Natural realistic variation with gentle baseline
  const baseScore = 65 + (i % 6) * 4 + Math.round(Math.sin(i / 3) * 6);
  const maxScore = 100;

  return {
    id: `sess-${i + 1}`,
    gameId: (domain === 'visual_spatial' ? 'memory_match' :
             domain === 'attention_motor' ? 'tea_garden' :
             domain === 'executive_function' ? 'brain_quest' :
             domain === 'pattern_logic' ? 'pattern_weave' :
             domain === 'temporal_orientation' ? 'routine_builder' :
             domain === 'auditory_memory' ? 'sounds_hills' : 'family_recall'),
    domain,
    timestamp: d.toISOString(),
    date: dateStr,
    score: Math.min(100, Math.max(50, baseScore)),
    maxScore,
    accuracy: Math.min(1, Math.max(0.5, baseScore / 100)),
    reactionTimeMs: Math.round(2200 + Math.cos(i) * 600),
    difficultyLevel: 1 + Math.floor(i / 10),
  };
});

export const folkSongs: FolkSongCard[] = [
  {
    id: 'fs-1',
    tuneId: 'bihu_spring',
    title: {
      en: 'Bihu Spring Pepa Melody',
      as: 'ৰঙালী বিহুৰ পেঁপা আৰু সুৰ',
      bn: 'রঙালী বিহুর বাঁশি ও ঢোলের সুর',
      hi: 'रोंगाली बिहू पेपा व ढोल की धुन',
      mni: 'Bihu Springgi Khonjel',
    },
    region: {
      en: 'Assam (Brahmaputra Valley)',
      as: 'অসম (ব্ৰহ্মপুত্ৰ উপত্যকা)',
      bn: 'আসাম (ব্রহ্মপুত্র উপত্যকা)',
      hi: 'असम (ब्रह्मपुत्र घाटी)',
      mni: 'Assam',
    },
    description: {
      en: 'The joyful spring buffalo horn flute (Pepa) melody played during Rongali Bihu as the orchids bloom.',
      as: 'কপৌ ফুল ফুলাৰ বতৰত ৰঙালী বিহুৰ মাঙ্গলিক সুৰ। ঢোল আৰু পেঁপাৰ চিৰসেউজ আনন্দ।',
      bn: 'বসন্তের শুরুতে অর্কিড ফোটার সময় ঐতিহ্যবাহী মহিষের শিঙের পেঁপা ও ঢোলের মিষ্টি সুর।',
      hi: 'वसंत ऋतु में कोपौ फूल खिलने पर बजने वाली पारंपरिक पेपा व ढोल की मधुर धुन।',
      mni: 'Bihugi matamda khongba fajaba makhon.',
    },
    imageUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=600&q=80',
    culturalMemory: {
      en: 'In village courtyards across Assam, families gather under the shade of mango trees as young dancers celebrate the coming of harvest.',
      as: 'গাঁৱৰ চোতালত আমৰ ছাঁত ডেকা-গাভৰুৱে বিহু নাচি নতুন বছৰক আদৰে।',
      bn: 'গ্রামের উঠোনে নতুন ফসলের আনন্দে পরিবার ও প্রিয়জনরা একত্রিত হয়।',
      hi: 'गांव के आंगनों में नई फसल और नए साल के स्वागत में सभी प्रियजन एक साथ मिलकर गीत गाते हैं।',
      mni: 'Yumgi manggonda meeyam punna haraoba matam.',
    },
  },
  {
    id: 'fs-2',
    tuneId: 'baul_melody',
    title: {
      en: 'Barak Valley Baul & Rabindra Melody',
      as: 'বাউল আৰু সুৰীয়া একতাৰা',
      bn: 'বরাক উপত্যকার বাউল ও রবীন্দ্র সঙ্গীত',
      hi: 'बराक घाटी की बाउल व एकतारा धुन',
      mni: 'Ektaragi Khonjel',
    },
    region: {
      en: 'Cachar & Bengal Heritage',
      as: 'বৰাক উপত্যকা আৰু কাছাৰ',
      bn: 'কাছাড় ও বরাক উপত্যকা',
      hi: 'कछार एवं बराक घाटी',
      mni: 'Barak Valley',
    },
    description: {
      en: 'Peaceful acoustic tones of the Ektara evoking riverside evenings by the Barak and Padma rivers.',
      as: 'বৰাক নদীৰ ঘাটত একতাৰা আৰু বাঁহীৰ শান্ত মৰমীয়া সুৰ।',
      bn: 'নদীর শান্ত ঘাটে গোধূলি লগ্নে মন জুড়ানো একতারা ও বাঁশির স্নিগ্ধ সুর।',
      hi: 'शांत नदी के किनारे बजने वाली एकतारा की सुमधुर व आध्यात्मिक धुन।',
      mni: 'Turel mapada khongba fajaba khonjel.',
    },
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80',
    culturalMemory: {
      en: 'Listening to the boatman singing folk songs as the crimson sunset settles over the river bend.',
      as: 'সন্ধিয়া বেলি লহিওৱা সময়ত নৈৰ ঘাটত নাৱৰীয়াৰ ভাটিয়ালী গীতৰ স্মৃতি।',
      bn: 'সূর্যাস্তের সময় নদীর শান্ত জলে মাঝির কণ্ঠে ভাটিয়ালী সুরের স্মৃতি।',
      hi: 'शाम के समय शांत नदी के किनारे माझी के सुरीले गीत सुनने का सुखद अनुभव।',
      mni: 'Numit thaba matamda turelda esahei taba.',
    },
  },
  {
    id: 'fs-3',
    tuneId: 'manipuri_pena',
    title: {
      en: 'Manipuri Pena & Temple Hymn',
      as: 'মণিপুৰী পেনা আৰু লাই হাৰাওবা',
      bn: 'মণিপুরী পেনা ও লাই হারাওবা সুর',
      hi: 'मणिपुरी पेना व लाई हाराओबा धुन',
      mni: 'Manipuri Pena amasung Lai Haraoba',
    },
    region: {
      en: 'Manipur (Imphal Valley & Loktak)',
      as: 'মণিপুৰ (ইম্ফল উপত্যকা)',
      bn: 'মণিপুর (ইম্ফল উপত্যকা)',
      hi: 'मणिपुर (इम्फाल घाटी)',
      mni: 'Manipur',
    },
    description: {
      en: 'The sacred, resonant bowed string of the ancient Pena played during morning prayers and festivals.',
      as: 'পবিত্ৰ পেনা বাদ্যৰ সুৰ, যিয়ে পূৱাৰ বতাহত শান্তি কঢ়িয়াই আনে।',
      bn: 'প্রাচীন ঐতিহ্যবাহী পেনা যন্ত্রের পবিত্র সুর, যা ভোরে মন্দিরে ও উৎসবে ধ্বনিত হয়।',
      hi: 'प्राचीन पारंपरिक पेना वाद्य की मधुर व शांत धुन, जो सुबह की प्रार्थना में बजती है।',
      mni: 'Lai Haraobagi matamda khongba Pena gi makhon.',
    },
    imageUrl: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80',
    culturalMemory: {
      en: 'Walking peacefully by Kangla Fort as the lotus flowers open in the morning mist.',
      as: 'পুৱাৰ কুঁৱলীৰ মাজত পদুম ফুলা পুখুৰীৰ পাৰেৰে শান্ত খোজেৰে খোজ কঢ়াৰ স্মৃতি।',
      bn: 'সকালের শান্ত বাতাসে পদ্মফোটা দিঘির পাড়ে ভোরের আলো দেখার স্মৃতি।',
      hi: 'सुबह की शांत हवा में कमल के तालाब के पास टहलने की सुखद यादें।',
      mni: 'Ayangba numitta thambal satpa yengba.',
    },
  },
  {
    id: 'fs-4',
    tuneId: 'hill_flute',
    title: {
      en: 'Khasi Hills Gentle Bamboo Flute',
      as: 'মেঘালয় পাহাৰৰ বাঁহীৰ সুৰ',
      bn: 'খাসি পাহাড়ের শান্ত বাঁশির সুর',
      hi: 'खासी पहाड़ियों की शांत बांसुरी',
      mni: 'Chinggi Wagi Makhon',
    },
    region: {
      en: 'Meghalaya (Shillong & Cherrapunji)',
      as: 'মেঘালয় (শ্বিলং আৰু চেৰাপুঞ্জী)',
      bn: 'মেঘালয় (শিলং ও চেরাপুঞ্জি)',
      hi: 'मेघालय (शिलांग व चेरापूंजी)',
      mni: 'Meghalaya',
    },
    description: {
      en: 'Soothing pentatonic bamboo flute melody echoing softly through pine forests and misty valleys.',
      as: 'চিৰাপুঞ্জীৰ পাইন বননি আৰু কুঁৱলীৰ মাজেৰে বৈ অহা পাহাৰীয়া বাঁহীৰ কোমল ধ্বনি।',
      bn: 'পাইন বনের মধ্য দিয়ে ভেসে আসা মিষ্টি পাহাড়ি বাঁশির সুর।',
      hi: 'देवदार व चीड़ के जंगलों से होकर गुजरने वाली पहाड़ी बांसुरी की शांत धुन।',
      mni: 'Ching gi nungsit oina lakpa wagi khonjel.',
    },
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    culturalMemory: {
      en: 'Sipping hot tea on a wooden veranda while watching clouds roll over the blue hills.',
      as: 'কাঠৰ বাৰাণ্ডাত বহি গৰম চাহৰ কাপ হাতত লৈ নীলা পাহাৰৰ বুকুত মেঘৰ খেলা চোৱাৰ আনন্দ।',
      bn: 'বারান্দায় বসে গরম চায়ের কাপে চুমুক দিয়ে মেঘের ওড়াউড়ি দেখার মুহূর্ত।',
      hi: 'पहाड़ी बरामदे में बैठकर गरम चाय की चुस्की लेते हुए बादलों को निहारने का सुकून।',
      mni: 'Cha thakna chinggi leichil yengba.',
    },
  },
  {
    id: 'fs-5',
    tuneId: 'temple_chime',
    title: {
      en: 'Kamakhya Temple Evening Bells',
      as: 'কামাখ্যাৰ সন্ধিয়াৰ কাঁহ-ঘণ্টা',
      bn: 'কামাখ্যা মন্দিরের সন্ধ্যার কাঁসা-ঘণ্টা',
      hi: 'कामाख्या मंदिर की संध्या घंटी व शंख',
      mni: 'Laisanggi Kangsi Makhon',
    },
    region: {
      en: 'Nilachal Hills, Guwahati',
      as: 'নীলাচল পাহাৰ, গুৱাহাটী',
      bn: 'নীলাচল পাহাড়, গুয়াহাটি',
      hi: 'नीलाचल पर्वत, गुवाहाटी',
      mni: 'Guwahati Nilachal',
    },
    description: {
      en: 'Deep bronze temple bells and conch shell resonance at sunset on Nilachal hill.',
      as: 'নীলাচলৰ বুকুত সন্ধিয়াৰ আৰতিৰ কাঁহ-ঘণ্টা আৰু শংখৰ পৱিত্ৰ ধ্বনি।',
      bn: 'সন্ধ্যা আরতির সময় কাঁসার ঘণ্টা ও পবিত্র শঙ্খের গভীর শান্তিময় ধ্বনি।',
      hi: 'संध्या आरती के समय पीतल की घंटी और शंख की पवित्र एवं शांत गूंज।',
      mni: 'Numidangwairam laisangda kangsi khongba.',
    },
    imageUrl: 'https://images.unsplash.com/photo-1545232979-fbf675951a83?auto=format&fit=crop&w=600&q=80',
    culturalMemory: {
      en: 'Lighting a brass oil lamp in the family prayer room as the distant temple bells chime.',
      as: 'ঘৰৰ নামঘৰ বা গোঁসাইঘৰত মাটিৰ চাকি জ্বলাই মনলৈ অহা পৰম শান্তিৰ অনুভূতি।',
      bn: 'সন্ধ্যার আলোয় তুলসীতলায় প্রদীপ জ্বালানোর সময় দূর থেকে আসা ঘণ্টার ধ্বনি।',
      hi: 'शाम को घर के मंदिर में दीपक जलाते समय आने वाली शांति और सुकून का अहसास।',
      mni: 'Yumgi thaomei thambada thouna phangba.',
    },
  },
];
